# GitHub Actions TeX workflow
#
# Created: 2021 by Vivien Richter <vivien-richter@outlook.de>
# License: CC BY 4.0
name: Build

# Controls when the action will run.
on:
  # Triggers the workflow on push request events but only for the $default-branch branch
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets environment variables
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Checks the repository out
      - name: Repository checkout
        uses: actions/checkout@latest
        with:
          lfs: true

      # Compiles the LaTeX document
      - name: Compile TeX
        uses: dante-ev/latex-action@latest
        with:
          root_file: doc.tex
          args: -xelatex

      # Stores the final PDF
      - name: Store PDF
        uses: actions/upload-artifact@latest
        with:
          name: Doc
          path: doc.pdf
