# GitHub Actions issue creation workflow

name: New issue

# Controls when the action will run.
on:
  # Triggers the workflow on issue creation events
  issues:
    types: [opened]

# Sets environment variables
env:
  ISSUE_ID: $(jq -r '.issue.id' < "$GITHUB_EVENT_PATH")
  ISSUE_TITLE: $(jq -r '.issue.title' < "$GITHUB_EVENT_PATH")
  PROJECT_BOARD_ISSUE_COLUMN_ID: 12890490 #${{ secrets.PROJECT_BOARD_ISSUE_COLUMN_ID }}
  API_AUTH_TOKEN_GITHUB: ${{ secrets.API_AUTH_TOKEN_GITHUB }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Project board
  assign_project:
    name: Assign issue to project board
    runs-on: ubuntu-latest
    steps:
      # Assign issue
      - name: Assign issue
        run: >
          curl --retry 3 --retry-delay 5 -u "$GITHUB_ACTOR:$API_AUTH_TOKEN_GITHUB" -H "Accept: application/vnd.github.inertia-preview+json" -X POST "$GITHUB_API_URL/projects/columns/$PROJECT_BOARD_ISSUE_COLUMN_ID/cards" -d "{\"content_type\": \"Issue\", \"content_id\": $ISSUE_ID}"
