# GitHub Actions issue creation workflow

name: New issue

# Controls when the action will run.
on:
  # Triggers the workflow on issue creation events
  issues:
    types: [opened]

# Sets environment variables
env:
  REQUEST_RETRY_NUMBER: 3
  REQUEST_RETRY_DELAY: 5 # in seconds
  API_URL_GITHUB: ${{env.GITHUB_API_URL}}
  API_URL_CLOCKIFY: ${{secrets.CLOCKIFY_API_URL}}
  API_AUTH_TOKEN_GITHUB: ${{secrets.API_AUTH_TOKEN_GITHUB}}
  API_AUTH_TOKEN_CLOCKIFY: ${{secrets.API_AUTH_TOKEN_CLOCKIFY}}
  API_USER_GITHUB: ${{env.GITHUB_ACTOR}}
  GITHUB_PROJECT_BOARD_COLUMN_ID: ${{secrets.PROJECT_BOARD_TODO_COLUMN_ID}}
  GITHUB_EVENT_OBJECT_PATH: ${{env.GITHUB_EVENT_PATH}}
  GITHUB_ENVIRONMENT: ${{env.GITHUB_ENV}}
  CLOCKIFY_WORKSPACE_ID: ${{secrets.CLOCKIFY_WORKSPACE_ID}}
  CLOCKIFY_PROJECT_ID: ${{secrets.CLOCKIFY_PROJECT_ID}}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Project board
  assign_project:
    name: Assign issue to project board
    runs-on: ubuntu-latest
    steps:
      # Collect required issue properties
      - name: Get issue ID
        run: echo "ISSUE_ID=$(jq -r '.issue.id' < $GITHUB_EVENT_OBJECT_PATH)" >> $GITHUB_ENVIRONMENT

      # Assign issue
      - name: Assign issue to project
        run: >
          curl --retry "$REQUEST_RETRY_NUMBER" --retry-delay "$REQUEST_RETRY_DELAY"
          -u "$API_USER_GITHUB:$API_AUTH_TOKEN_GITHUB"
          -H "Accept: application/vnd.github.inertia-preview+json"
          -X POST "$GITHUB_API_URL/projects/columns/$GITHUB_PROJECT_BOARD_COLUMN_ID/cards"
          -d "{\"content_type\": \"Issue\", \"content_id\": ${{env.ISSUE_ID}}}"

  # Time tracking system
  create_task:
    name: Create task at time tracking system
    runs-on: ubuntu-latest
    steps:
      # Collect required issue properties
      - name: Get issue ID and title
        run: |
          echo "ISSUE_ID=$(jq -r '.issue.id' < $GITHUB_EVENT_OBJECT_PATH)" >> $GITHUB_ENVIRONMENT
          echo "ISSUE_TITLE=$(jq -r '.issue.title' < $GITHUB_EVENT_OBJECT_PATH)" >> $GITHUB_ENVIRONMENT

      # Create task
      - name: Create task at time tracking system
        run: >
          curl --retry "$REQUEST_RETRY_NUMBER" --retry-delay "$REQUEST_RETRY_DELAY"
          -H "Content-Type: application/json"
          -H "X-Api-Key: $API_AUTH_TOKEN_CLOCKIFY"
          -X POST "$CLOCKIFY_API_URL/workspaces/$CLOCKIFY_WORKSPACE_ID/projects/$CLOCKIFY_PROJECT_ID/tasks"
          -d "{\"name\": #${{env.ISSUE_ID}} ${{env.ISSUE_TITLE}}}"
