# GitHub Actions TeX release workflow
#
# Created: 2021 by Vivien Richter <vivien-richter@outlook.de>
# License: CC BY 4.0
name: Release

# Controls when the action will run.
on:
  # Triggers the workflow on push tag events
  push:
    tags:
      - "v*.*.*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets environment variables
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      # Get the release name by the tag message title
      - name: Get release name
        run: echo "RELEASE_NAME=$(git tag -l --format='%(contents:subject)' ${{github.ref}})" >> $GITHUB_ENV
        
      - name: test
        run: echo ${{github.ref}})

      # Publish the release
      - name: Publish release
        uses: actions/create-release@v1
        with:
          tag_name: ${{github.ref}}
          release_name: Release ${{env.RELEASE_NAME}}
          draft: false
          prerelease: false
