# GitHub Actions TeX release workflow
#
# Created: 2021 by Vivien Richter <vivien-richter@outlook.de>
# License: CC BY 4.0
name: Release

# Controls when the action will run.
on:
  # Triggers the workflow on push tag events
  push:
    tags:
      - "v*.*.*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets environment variables
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      # Get the tag name
      - name: Get tag name
        run: echo "TAG_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      # Check the repository out
      - name: Repository checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      # Get the release title and description by the tag message title
      - name: Get release details
        run: |
          echo "TAG_SUBJECT=$(git tag -l --format='%(contents:subject)' ${{env.TAG_NAME}})" >> $GITHUB_ENV
          echo "TAG_BODY=$(git tag -l --format='%(contents:body)' ${{env.TAG_NAME}})" >> $GITHUB_ENV

      # Publish the release
      - name: Publish release
        uses: actions/create-release@v1
        with:
          tag_name: ${{github.ref}}
          release_name: ${{env.TAG_SUBJECT}}
          body: ${{env.TAG_BODY}}
          draft: false
          prerelease: false
