# GitHub Actions release workflow
#
# Created: 2021 by Vivien Richter <vivien-richter@outlook.de>
#
# License: CC BY 4.0
name: Release

# Controls when the action will run.
on:
  # Triggers the workflow on workflow_run events but only for the same branch and if completed.
  workflow_run:
    workflows:
      - Build
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets environment variables
env:
  REQUEST_RETRY_NUMBER: 3
  REQUEST_RETRY_DELAY: 5 # in seconds
  API_URL_GITHUB: ${{github.api_url}}
  # This token is provided by Actions, you do not need to create your own token
  GITHUB_TOKEN: ${{github.token}}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    name: Release 🎉
    runs-on: ubuntu-latest
    steps:
      # Checks CI result
      - name: Check CI result
        run: >
          RUN_CONCLUSION=$(curl -s --retry "$REQUEST_RETRY_NUMBER" --retry-delay "$REQUEST_RETRY_DELAY"
          -H "Accept: application/vnd.github.v3+json"
          -X GET "$API_URL_GITHUB/repos/vivi90/test/actions/workflows/unity_ci.yml/runs"
          -d "{\"content_type\": \"Issue\", \"content_id\": ${{env.ISSUE_ID}}}"
          | jq -r '.workflow_runs[0].conclusion')

          if [ "$RUN_CONCLUSION" != "success" ]; then
            exit 1;
          fi

      # Loads build workflow artifacts
      - name: Load build artifacts
        uses: dawidd6/action-download-artifact@v2.11.1
        with:
          workflow: unity_ci.yml
          workflow_conclusion: success
          name: Builds
          path: Builds

      # Shows loaded files
      - name: Display structure of downloaded files
        run: ls -R Builds

      # Creates release
