# GitHub Actions TeX release workflow
#
# Created: 2021 by Vivien Richter <vivien-richter@outlook.de>
# License: CC BY 4.0
name: Release

# Controls when the action will run.
on:
  # Triggers the workflow on push tag events
  push:
    tags:
      - "v*.*.*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      # Tag read
      - name: tag read
        run: echo git tag -l --format='%(contents:subject)' ${GITHUB_REF#refs/*/}
