name: Actions 😎

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets environment variables
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v2.1.4
        with:
          path: Library
          key: Library

      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v2.0-alpha-2
        with:
          unityVersion: ${{ secrets.UNITY_VERSION }}
          customParameters: -nographics # required für Unity v2019.4.x and 2020.x

      # Cleanup
      - name: "Freeing up disk space"
        run: |
          echo "############################################"
          echo "#    Freeing up disk space on CI system    #"
          echo "############################################"
          echo -n "Disk space before:"
          df -h / --output=avail | tail -1
          # https://github.com/apache/flink/blob/master/tools/azure-pipelines/free_disk_space.sh
          rm -rf /usr/share/dotnet/
          # https://github.com/actions/virtual-environments/issues/709#issuecomment-612569242
          rm -rf "/usr/local/share/boost"
          rm -rf "$AGENT_TOOLSDIRECTORY"
          echo -n "Disk space after:"
          df -h / --output=avail | tail -1

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2.0-alpha-6
        with:
          unityVersion: ${{ secrets.UNITY_VERSION }}
          targetPlatform: Android
          allowDirtyBuild: true

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
